language: node_js
cache: yarn
node_js:
  - "7"
script: yarn run build:CI
after_success:
  # Send coverage data to coveralls.
  - yarn run test:cover:CI

before_deploy:
 - ./tools/deploy/before_deploy.sh

deploy:
  provider: azure_web_apps
  on: master
  verbose: true
  #https://docs.travis-ci.com/user/deployment/#Uploading-Files
  skip_cleanup: true
