language: node_js
cache: yarn
node_js:
  - "7"
script: yarn run test:CI
after_success:
  # Send coverage data to coveralls.
  - yarn run test:cover:CI

before_deploy: "yarn run build:CI && cat .gitignore | grep -v ^dist$ > temp.gitignore && mv temp.gitignore .gitignore && rm -rf node_modules coverage && cp tools/deploy/web.config.sample dist/web.config"

deploy:
  provider: azure_web_apps
  on: master
  verbose: true
  #https://docs.travis-ci.com/user/deployment/#Uploading-Files
  skip_cleanup: true
