export const QUESTIONNAIRE_LIST_LOADED = "QUESTIONNAIRE_LIST_LOADED";
export const QUESTIONNAIRE_LOADED = "QUESTIONNAIRE_LOADED";

export const FETCH_EXTERNAL_VALUE_SET = "FETCH_EXTERNAL_VALUE_SET";
export const FETCH_RELATIVE_VALUE_SET = "FETCH_RELATIVE_VALUE_SET";
