export const QUESTIONNAIRE_LIST_LOADED = "QUESTIONNAIRE_LIST_LOADED";
export const QUESTIONNAIRE_LOADED = "QUESTIONNAIRE_LOADED";
export const QUESTIONNAIRE_LIST_FILTER = "QUESTIONNAIRE_LIST_FILTER";
export const FETCH_RESOURCE = "FETCH_RESOURCE";
export const QUESTIONNAIRE_SET_ANSWER = "QUESTIONNAIRE_SET_ANSWER";
